version: '3.8'
services:
  
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - ./data/zookeeper/data:/var/lib/zookeeper/data
      - ./data/zookeeper/logs:/var/lib/zookeeper/log
    ports:
      - 2181:2181
  
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 

  producer:
    container_name: producer
    build: ./producer
    ports:
      - 7001:8080
    volumes:
      - ./data/producer:/app
    environment:
      - PORT=8080
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=my_topic_1
    depends_on:
      - kafka

  consumer:
    container_name: consumer
    build: ./consumer
    ports:
      - 7002:8080
    volumes:
      - ./data/consumer:/app
    environment:
      - PORT=7002
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=my_topic_1
    depends_on:
      - kafka